
import React, { Component } from "react";
import {
  Grid,
  Row,
  Col,
  FormGroup,
  ControlLabel,
  FormControl
} from "react-bootstrap";

import { Card } from "components/Card/Card.jsx";
import { FormInputs } from "components/FormInputs/FormInputs.jsx";
import { UserCard } from "components/UserCard/UserCard.jsx";
import Button from "components/CustomButton/CustomButton.jsx";

import avatar from "assets/img/faces/face-3.jpg";

function Submission(props) {
  
    return (
      <div className="content">
        <Grid fluid>
          <Row style={{marginBottom:"1rem"}}>
            <span style={{fontSize: '2rem',marginRight:'2rem'}}>Assignment 1: Algebra Exercise</span>
            <Button bsStyle="info" simple type="button" bsSize="l" fill="blue">
                <i className="fa fa-edit" >Submit</i>
              </Button>
          </Row>
          <Row style={{marginBottom:"1rem"}}>
            <Col md={3}>
              <div> <b>Due</b>  Oct 10 by 6pm</div>
            </Col>
            <Col md={3}>
              <div><b>Points</b>  3</div>
            </Col>
            <Col md={3}>
              <div><b>Submitting</b>  a file upload</div>
            </Col>
          </Row>
          <Row>

          <Card
                statsIcon="fa fa-history"
                id="chartHours"
                title="Submission Guidelines"
                stats="Updated 2 hours ago"
                content={
                  <div>
            
                  <p>&nbsp;</p>
                  <p>You need to submit three files, program output, the png file generated by the program (i.e., 5 gram.png), and your python script. After you finish the assignments, make sure you include your name and student ID in the beginning of your code.</p>
                  <p># author : Your name</p>
                  <p># student id : Your student ID</p>
                  <p>
                    Copy all the program output to a text file named StudentID assignment3 output.txt. Rename the png file generated by the program as StudentID 5 gram.png. Rename your python script solution as StudentID assignment3.py. Zip them altogether and submit it to Canvas. Similar with the previous assignments, there’s no strict restrictions on the output formats. You could define your format.
                  </p>
                  
                  </div>
                }/>
            
          </Row>
        </Grid>
      </div>
    );
  
}

export default Submission;